<a href="https://colab.research.google.com/github/KennyTC/numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To learn numpy effeciently

In [3]:
import numpy as np


Data type	Description
1. bool_	Boolean (True or False) stored as a byte
2. int_	Default integer type (same as C long; normally either int64 or int32)
3. intc	Identical to C int (normally int32 or int64)
2. intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
3. int8	Byte (-128 to 127)
4. int16	Integer (-32768 to 32767)
5. int32	Integer (-2147483648 to 2147483647)
6. int64	Integer (-9223372036854775808 to 9223372036854775807)
7. uint8	Unsigned integer (0 to 255)
8. uint16	Unsigned integer (0 to 65535)
9. uint32	Unsigned integer (0 to 4294967295)
10. uint64	Unsigned integer (0 to 18446744073709551615)
11. float_	Shorthand for float64.
12. float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
13. float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
14. float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
15. complex_	Shorthand for complex128.
16. complex64	Complex number, represented by two 32-bit floats
17. complex128	Complex number, represented by two 64-bit floats

# Create 

In [13]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, size=(3, 3))

array([[0, 2, 9],
       [2, 6, 3],
       [2, 5, 7]])

In [5]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.34843069, 0.12778805, 0.68332844],
       [0.52060017, 0.11624614, 0.57760463],
       [0.63491414, 0.82753647, 0.01908932]])

In [9]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(2, 100, (3, 3))

array([[  21.83594095,  -17.09685113,  -60.48004432],
       [-134.2452124 ,   21.62396117,   -7.52001065],
       [ -11.92666223,   22.89443057,   57.17462532]])

In [18]:
# check size, itemsize and nbyte
a = np.random.randint(10, size=(2,3,4))
print(a.dtype, a.itemsize, a.size)
assert a.nbytes == a.itemsize * a.size

int64 8 24


# Subarrays as no-copy views

In [24]:
# a subset in numpy array is a view, ie. any change to a view will effect the origin, while List in python is a copy
a = np.random.randint(10, size=(3,3))
b = a[1:, 1:]
print(a)
print(b)
b[0,0]=7
print(a)
# if we want to copy, not a no-copy view:
c = a.copy()

[[2 1 1]
 [7 3 4]
 [1 5 0]]
[[3 4]
 [5 0]]
[[2 1 1]
 [7 7 4]
 [1 5 0]]


# Reshape

In [25]:
x = np.array([1, 2, 3])

# row vector via reshape
print(x.reshape((1, 3)))
print(x[np.newaxis,:])


[[1 2 3]]
[[1 2 3]]


In [27]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
s = np.vstack([x, grid])
print(s)

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [29]:
np.vsplit(s, [1])

[array([[1, 2, 3]]), array([[9, 8, 7],
        [6, 5, 4]])]